### ISSUE TITLE
Great Plugin, few suggestions :)

### ISSUE THREAD

**Issue by dummifiedme** [delashum/obsidian-checklist-plugin#1]
I have been using this plugin for some days now.  I noticed a few problems, if you could fix them it would be great :)

1. Doesn't accept the links. I mean, the links are displayed as text.
    - Either should be like a preview or atleast highlighted like a link?
2. The sub-list are shown without indentation. And shown even if there is not #todo tag on those lines. I guess, it just takes the whole block and displays it over there. Even if there is no `- [ ]`  in a line, it will display it there in the checklist.

Suggestions:
- If we could integrate dates as well? and sort the list according to dates. I mean, we can have something like `#todo @[[date dage]]`, it would be a healthy enhancement.

I am anyway thankful for the plugin :)
These are just my suggestions,

**Comment by delashum** [comment]
Thanks! These are good suggestions.

 #1 is already on my list; my plan was to display them as a link and clicking on it would take you to that page. Would that accomplish what you were hoping for?

#2 i'm not 100% sure what you mean. Are you saying that if you have indented checklist items they should show indented in the sidebar? Current implementation should only pull in lines that start with `- [ ]`, so if it's pulling in other lines that's a bug. Also, the #tag does work on a block level only currently. I was thinking about maybe letting you tag individual lines with it to pull them in without pulling the rest of the block

Hmm, that's an interesting suggestion. Do you mean kind of like a due date? I like it! I'll work on something for that.

**Comment by dummifiedme** [comment]
> #1 is already on my list; 
Glad to know! Yes, that would solve it for me. Preferably, it should be like a preview not with the `[[ ]] `

As for the point 2, currently it pulls the whole block with checklists. I meant, it pulls it and shows them even when they don't have the #todo tag and that too out of indentation.

So either just pull one line, or maintain the indent. Anything will do for me. Second one seems better since having many #todo tags might look redundant in an indented list of things.

As for the due dates,yes,you can devise a system ao denoting the due dates. Using `@[[day page]]` just like you search for a #todo. Or any symbol for that matter. Further, you can give an option of sorting due date wise.

**Comment by phibr0** [comment]
I am not sure if i should create a new issue or if it makes sense to put it here

But i usually use markdown in my todolists to make important things **bold**, would it be possible to enable this formatting? It only show the \*\* in my View

**Comment by delashum** [comment]
Yep, good idea! coming soon

**Comment by delashum** [comment]
@dummifiedme i'm going to close this out, bold, italic and links are supported now. Need to spend some more time thinking about how indentation and due dates work though. Will come in a later release

**Comment by delashum** [comment]
One thing to add to that ^ With links, they will now display as link, and hover works *sometimes*. There is limited documentation of the plugin API, and I am having a hard time figuring out the right way to do that. I will revisit this, but this should get you by for now
