### ISSUE TITLE
The plugin it's not working properly

### ISSUE THREAD

**Issue by EhuddR** [delashum/obsidian-checklist-plugin#10]
![image](https://user-images.githubusercontent.com/78237982/106334726-438f2c80-6259-11eb-8dea-feb86b65c63b.png)
The plugin does not display any task in the box. Previously it displayed all my tasks normally.
The only change I made was to "tag: todo" to "tag: tareas"

**Comment by delashum** [comment]
Do you have any checklists tagged with `#tareas`, because if not, then that is the expected behavior.

**Comment by torstenkoepke** [comment]
Try to edit one of your files with tasks (including a #tareas, as delashum wrote), that seems to solve the exact same issue for me.

**Comment by EhuddR** [comment]
![image](https://user-images.githubusercontent.com/78237982/106403155-2db96d00-63fb-11eb-8366-9fe2bf02e075.png)
![image](https://user-images.githubusercontent.com/78237982/106403267-acaea580-63fb-11eb-9594-6c740e8aa010.png)
![image](https://user-images.githubusercontent.com/78237982/106403301-ea133300-63fb-11eb-9530-9d0f1608dcc4.png)

Hello, thank you for your prompt reply. However, it does not seem to be working. Attached, I am sending you images of the configuration I have and one of my notes. I also created a file to test using the same schema as the plugin example but it doesn't seem to work. 
The plug in was working normally in version 1.04.

**Comment by mabiga** [comment]
Hi,
first of all thank you for this great plugin. 
Unfortunately I have the same issue as EhuddR.
It also worked with version 1.04 for me.

**Comment by delashum** [comment]
In your last screenshot it looks like you are making your checklist items with `* [ ]` rather than `- [ ]`, or is that just a styling thing? Because currently the parse is only searching for lines that begin with a dash. I am currently on `1.0.6` on my machine and it seems to be working fine so hard for me to diagnose this.

**Comment by EhuddR** [comment]
> In your last screenshot it looks like you are making your checklist items with `* [ ]` rather than `- [ ]`, or is that just a styling thing? Because currently the parse is only searching for lines that begin with a dash. I am currently on `1.0.6` on my machine and it seems to be working fine so hard for me to diagnose this.

Hi! It's just the style of the obsidianite theme. All my tasks are done with - [ ]
I do not know if this error is due to some conflict with another plugin.
The list of installed Plugins is as follows:
- Calendar
- Citations
- Day Planner
- Mind Map
- Note Refractor
- Reading Time
- Slading Panes
- Templater
- Text Expand
- Journey

**Comment by jensuj** [comment]
I have the same problem as described above..
Obsidian v0.10.12
Checklist v1.0.6

The plugin works sporadically. Some times the "checklist" pane is empty, other times it only has a chelists from the current open pane, other times, it has all checklists in the vault.

It seems like updating the tag (rewriting "todo") in the settings can help the plugin fetch all lists, but it's not a sure fix.

**Comment by delashum** [comment]
I will look into this some more this week, I have a few ideas I can try. My first hypothesis is that is has to do with the amount of files in your vault. My personal vault that i do most of my testing on is relatively small, so the time it takes the vault to boot up is fairly short. Do any of you that are having problems have very large vaults?

**Comment by EhuddR** [comment]
Thanks! I have a mid size vault. Around 300 files.

**Comment by delashum** [comment]
I am able to reproduce now as it is occurring in my vault now. It appears the fileCache isn't being updated as it once was. I will reach out to the plugin SDK maintainers to see what's going on

**Comment by delashum** [comment]
I just pushed `1.0.7` which is more smart about the way it loads files to ensure they are always loaded. Please let me know if this doesn't fix the issue

**Comment by EhuddR** [comment]
I am sorry to report that the plugin does not seem to work with a large number of files with tasks. It now shows a loading icon that keeps loading forever. Version 1.0.8

![image](https://user-images.githubusercontent.com/78237982/106709922-32308200-65c3-11eb-815b-0c5f355f72e7.png)


> I just pushed `1.0.7` which is more smart about the way it loads files to ensure they are always loaded. Please let me know if this doesn't fix the issue

**Comment by jensuj** [comment]
Updated, and it seems like it works as it should.

**Comment by delashum** [comment]
@EhuddR hmm, can you tell me if there are any errors in your console? 300 files should be no problem

**Comment by jlcala** [comment]
> @EhuddR hmm, can you tell me if there are any errors in your console? 300 files should be no problem

I'm getting the same forever loading icon as @EhuddR. I uninstalled every plugin I had except calendar, and my console has this error:

```
app.js:1 Obsidian Developer Console
VM95:543 Uncaught (in promise) TypeError: Cannot read property 'filePath' of undefined
    at eval (eval at <anonymous> (app.js:1), <anonymous>:543:53)
    at Array.map (<anonymous>)
    at decorateChunks (eval at <anonymous> (app.js:1), <anonymous>:532:19)
    at formTodo (eval at <anonymous> (app.js:1), <anonymous>:517:27)
    at findAllTodosFromTagBlock (eval at <anonymous> (app.js:1), <anonymous>:495:17)
    at eval (eval at <anonymous> (app.js:1), <anonymous>:428:48)
    at Array.flatMap (<anonymous>)
    at eval (eval at <anonymous> (app.js:1), <anonymous>:428:31)
    at Array.flatMap (<anonymous>)
    at parseTodos (eval at <anonymous> (app.js:1), <anonymous>:427:10)
```

**Comment by delashum** [comment]
Just released `1.0.9`, a bit of a shot in the dark based on that error, but I'm hopeful. Just let me know if you're still having issues

**Comment by mabiga** [comment]
Seams like you fixed the issue. At least for me its working nicely again.
Obsidian 0.10.11 and Plugin 1.0.9 for about 200 files in the vault.

**Comment by jlcala** [comment]
It's working for me! Thanks very much!

**Comment by EhuddR** [comment]
Thank you very much! Now it works correctly.
