### ISSUE TITLE
issue : cannot filter like #todo_xxx style list.

### ISSUE THREAD

**Issue by leeyaunlong** [delashum/obsidian-checklist-plugin#102]
issue : cannot filter like #todo_xxx style list.

**Comment by delashum** [comment]
What does this mean?

**Comment by leeyaunlong** [comment]
> What does this mean?

If i create the #todo_a, #todo_b, #todo_c tags, then set checklist-plugin filter word to "todo_" or "todo", the checklist-plugin cannot find out #todo_a, #todo_b.

Can you do some changes support aaa_bbb type tags with filter pattern "aaa_" ?
thanks,.

**Comment by delashum** [comment]
The currently supported syntax is slashes instead of underscores. e.g. #todo/a #todo/b #todo/c

No plans to support underscores at this time. Hopefully that works for you!

**Comment by leeyaunlong** [comment]
thanks
