### ISSUE TITLE
Leaving Tag Name Empty is not working on mobile

### ISSUE THREAD

**Issue by mrkteq** [delashum/obsidian-checklist-plugin#103]
When clearing the Tag Name field in settings, the leading # character cannot be removed and therefore the Todo List Pane is continually empty and cannot find any tasks. 
This is working correctly on desktop (Mac and Windows).
But it's not working on iOS 15.1 (iPhone XR).

**Comment by delashum** [comment]
can confirm this is happening. the problem is I still do not know how to debug on mobile so not sure what I can do about this one for now..

**Comment by NomarCub** [comment]
For debugging on mobile, there was this post in an Obsidian release

> There is now a mobile emulation flag that can be used to emulate mobile mode. Use `app.emulateMobile(true)` to turn on emulation and `app.emulateMobile(false)` to turn off.

[For android](https://discord.com/channels/686053708261228577/840286264964022302/862275992605425684) there's `chrome://inspect`.

There's also [this plugin](https://github.com/KjellConnelly/obsidian-dev-tools).

**Comment by delashum** [comment]
Can anyone confirm if this is still happening on version `2+`? Thanks for you tip about the emulation flag @NomarCub, turning that on locally I can't seem to repro it anymore

**Comment by NomarCub** [comment]
It could be that the actual mobile app is behind with some versions. My android app doesn't even have live previews yet.

**Comment by delashum** [comment]
I mean `2+` version of the checklist plugin. The latest is `2.0.1`

**Comment by flankstaek** [comment]
Please download the latest update and try again.

**Comment by mrkteq** [comment]
Downloaded 2.2.3 and this is working correctly on mobile now.
