### ISSUE TITLE
Issue: Failed to load plugin obsidian-checklist-plugin

### ISSUE THREAD

**Issue by EmSixTeen** [delashum/obsidian-checklist-plugin#104]
When I try to enable the plugin, I receive the following error:

> Failed to load plugin obsidian-checklist-plugin

**OS:** Windows 10 Enterprise N (Version 1909)
**Obsidian version:** v0.12.19
**Plugin version:** 1.2.3

**Comment by delashum** [comment]
Hmm, I'm probably going to need more details than that. Any errors in the console?

**Comment by EmSixTeen** [comment]
This is what I'm seeing:
```
app.js:1 
Plugin failure: obsidian-checklist-plugin Error: ENOENT: no such file or directory, open 'C:\Users\Aaron\iCloudDrive\iCloud~md~obsidian\Obsidian Notes\.obsidian\plugins\obsidian-checklist-plugin\main.js'
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
a @ app.js:1
Promise.then (async)
l @ app.js:1
(anonymous) @ app.js:1
D @ app.js:1
t.enablePlugin @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
D @ app.js:1
t.enablePluginAndSave @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
D @ app.js:1
(anonymous) @ app.js:1
e.setValue @ app.js:1
e.onClick @ app.js:1
```
<img width="739" alt="Obsidian_R2f34gO3X7" src="https://user-images.githubusercontent.com/149746/148747314-bf120900-d681-4201-ad58-0e1aedaccea2.png">

**Comment by AndrewNatoli** [comment]
Hey @EmSixTeen - Judging by the error it looks like the plugin might not have installed properly. Have you had any luck with using this since you last posted? 

Wondering if maybe Obsidian didn't install the files properly _or_ there was an issue with iCloud sync that either deleted or didn't properly sync one of the source files.

**Comment by EmSixTeen** [comment]
Tried removing and adding again once before but didn't help, but just tried there now after reading this and.. voilà? Enabled! Cheers. Wonder why it messed up in the first place? Guess you're right, iCloud Drive could well be the suspect.
