### ISSUE TITLE
task sorting options

### ISSUE THREAD

**Issue by jlcala** [delashum/obsidian-checklist-plugin#12]
Would it be possible to have the option to sort tasks by the page name they are on? 

For example, I keep my tasks on the day they are due. If I could sort the tasks in the checklist plugin by the page they are on they would always be in chronological order. Because we only have the option to sort by date modified, adding a new task to a page in the future makes it either the first or last on the list. 
![image](https://user-images.githubusercontent.com/69041809/106788995-af89e000-661f-11eb-9d15-7c4c23960d6e.png)
You can see the dates are out of order because I've been updating tasks.

The sort dropdown could be old -> new, new -> old, page a -> z, page z -> a

Thanks very much!

**Comment by delashum** [comment]
I have a task on my list to add support for due dates on tasks. I'm thinking of a syntax something like
```
- [ ] Some task [>02/10/2021]
```
And you would have an option to sort tasks by when they are due. Then you can still keep the tasks in context of where you created them. Would this solution work for you?

**Comment by jlcala** [comment]
Not really - I have my tasks on the date they belong to already, so I'd have to go back through and add this new date format to each of those tasks. 

Also, would we have to have the [[02-10-2021]] and [>02/10/2021] on the same line if we wanted the task to also show up in the backlinks of the target page?

**Comment by delashum** [comment]
Added new sorting options in latest release
