### ISSUE TITLE
Please Add Tutorial on Glob Pattern to Obsidian Plugin Page

### ISSUE THREAD

**Issue by TheOrangeQ** [delashum/obsidian-checklist-plugin#120]
Please add a short tutorial on how to use the "Include Files" setting properly. 

Not everyone using your plugin is a coder or knows what a Glob Pattern even is let alone what _"Include all files that match this glob pattern (e.g. "{*,!(exclude)/**/*}" includes all files except those in the exclude directory)."_ means. I've tried googling it and figuring it out from there but apparently I've got it wrong because what I've tried changes absolutely nothing. 

If I want to include all files in a certain folder how do I do it? 

I'm asking because it's taking forever to refresh or load the checklist and I'm hoping that if I limit the files it searches to just my task-planning folder it'll help make it load faster.

**Comment by mruderman** [comment]
Thank you for creating this plugin. I am also having trouble using the glob pattern example to create working exclusion directories. I don't know that you need a tutorial on this. Simply having a hypothetical example to map onto the generalized syntax.

**Comment by briarrrn** [comment]
What's worked for me so far is literally just putting the name of the folder I wanted to exclude inside the parenthesis of the example. eg "{,!(999 Templates)/**/*}"

**Comment by smile4yourself** [comment]
I tried: {,!(Bins Books Images Sources templates)/**/*} in order to exclude these directories located in my vault:
Bins, Books, Sources, templates,
but the plugin never finished loading. Then I tried using quotes around it... 
"{,!(Bins Books Images Sources templates)/**/*}" and the plugin did nothing; I removed the quotes, and then the plugin worked with:
{,!(Bins Books Images Sources templates)/**/*}
I have no idea why... fyi

**Comment by lynhai** [comment]
> What's worked for me so far is literally just putting the name of the folder I wanted to exclude inside the parenthesis of the example. eg "{,!(999 Templates)/**/*}"

It also works for me when putting the name of the folder I want to **include** in the parenthesis. eg "{(01 Diary)/**/*,}".

**Comment by janellchao** [comment]
After trying a dozen times, this has worked for me `{,!(Template)/**} `

**Comment by flankstaek** [comment]
Hey - I'm sorry you experienced problems trying to get it to work. The glob pattern matching is slightly simplified in the newest release and I've added some additional documentation to the [README](https://github.com/delashum/obsidian-checklist-plugin#glob-file-matching) that hopefully helps - let me know if you're still experiencing problems.
