### ISSUE TITLE
Checklist cannot be enabled on iPad OS 15.3.1 and Obsidian 1.0.1

### ISSUE THREAD

**Issue by GitHub-WBJ** [delashum/obsidian-checklist-plugin#123]
Checklist cannot be enabled on iPad OS 15.3.1 and Obsidian 1.0.1

**Comment by Snaity** [comment]
+1. Cannot be enabled on Samsung Galaxy version 9 and Obsidian 1.0.1

**Comment by dmkravets** [comment]
Cannot enable on ios mobile, either on latest version 1.1 Obsidian

**Comment by Rakerblad** [comment]
Unable to enable.
ios 15.4
12 pro max

**Comment by masteratrus** [comment]
Error state continues to exist on iPad and iOS 15.4.1. Anything I can help test?

**Comment by cafecitopuro** [comment]
same, unable to enable on ios 15.3 (iphone 13) and obsidian 1.1

**Comment by zzzgithubzzz** [comment]
> same, unable to enable on ios 15.3 (iphone 13) and obsidian 1.1

Same issue

**Comment by salutjesuispaul** [comment]
Same problem

**Comment by maksim77** [comment]
Same problem...

**Comment by tyoung560** [comment]
Same problem

Obsidian v1.2.3
iPadOS v15.5

**Comment by flankstaek** [comment]
Please download the latest update and try again.
