### ISSUE TITLE
Add shortcuts: Quickly switch windows

### ISSUE THREAD

**Issue by Kolooooo** [delashum/obsidian-checklist-plugin#128]
添加快捷键以达到能快速切换列表窗口，比如：
![Untitled 17 36 13](https://user-images.githubusercontent.com/19557102/160264084-720ba4a0-fb5b-4e4f-8951-1909d717293f.gif)

**Comment by flankstaek** [comment]
You should be able to add this via the hotkeys menu - look for the command `Checklist: Show Checklist Pane`
![image](https://user-images.githubusercontent.com/791577/195707111-bb0643b0-8c74-4d25-9724-77ce3f1034a6.png)
