### ISSUE TITLE
Only lowercase tags are working

### ISSUE THREAD

**Issue by MasterEnsis** [delashum/obsidian-checklist-plugin#135]
I just installed the plugin, I think it is fantastic and provides the solution to a problem I was thinking about how to fix.

Until now I have used the tag #To-Do. I added it to the tag name list (capitalized) but the tasks only show up on the sidebar, if I write the tag on the page in lowercase letters.

So #to-do will work, but #To-Do won't.

In the selection-box on the sidebar, about which tags you want to display, the tags from the list are displayed completly in lower case as well.

| Tag | Result | 
|:----|:---------|
| todo | ✔ |
| ToDo | ❌ |
| to-do | ✔ |
| To-Do | ❌ |
| to_do | ✔ |
| To_Do | ❌ |

Is there a way to make the tag-recognition either not case-sensitive or make it accept tags with uppercase letters?

**Comment by kerbless** [comment]
Quote, "JD" doesn't work, looks like the plugin changes to lowercase the

**Comment by kerbless** [comment]
### I have encountered the same issue
Looking at the images it seems like the #JD tag is resolved as #jd and so it doesn't work.
![image](https://user-images.githubusercontent.com/32358946/176203495-f1121251-e22c-47ed-aced-aa4bb0336df4.png)
![image](https://user-images.githubusercontent.com/32358946/176203774-14169381-a4e1-477b-bce9-3c5a0ceb11c3.png)
