### ISSUE TITLE
'Tag Name' not working - Unable to create checklists or do anything

### ISSUE THREAD

**Issue by table9gaming** [delashum/obsidian-checklist-plugin#139]
just installed this from a reccomended video, it doesn't work at all. I looked around and saw that there are a number of issues up right now, I tried it on my android note 10+ and i couldn't even install it. I looked at the console but I don't seem to see where there are any errors getting outputted - is there anyway my logs could help? 

I was really looking forward to this plugin but i guess i joined at the wrong time , lol

**Comment by AndEliRich** [comment]
Same for me on iPhone 13 pro max. I actually used this plug-in in the past and it worked but now it won’t even load.

**Comment by chrisgmbishop** [comment]
Can confirm same issue here. Long time user and latest update seems to have broken things. Everything was working fine before this version, 2.1.0, release

**Comment by flankstaek** [comment]
Please download the latest update and try again.

**Comment by flankstaek** [comment]
So just to confirm - you are unable to use the plugin at all on your iPhone after the latest release?

**Comment by chrisgmbishop** [comment]
Hey thanks. I'm not able to use it anywhere. Desktop or mobile. Though I don't use it on mobile.
I've tried manual refresh as well, with no luck.

**Comment by chrisgmbishop** [comment]
I've got task tasks Task Tasks and I get the note "No checklists found for tags: #task #task" in the Checklist panel
