### ISSUE TITLE
Use without tag?

### ISSUE THREAD

**Issue by Gnopps** [delashum/obsidian-checklist-plugin#14]
Thanks for developing this plugin, it is very useful!

The one thing I'm struggling with though is that I always have to add the #-tag. Would it be possible to make it work without the #-tag? For me, this just adds double work.

Usually my notes will look something like this:

> - Mike mentioned need to clean up
> - [ ] Clean up room
> - Discussion if we should paint the wall green or blue
> - Decided on blue paint
> - [ ] Buy blue paint

This would require me to either add the #-tag add the top of the list or for every item, instead of just adding the [ ]. 

So, would a setting to have it scan for all checkboxes, no matter what tag, be possible?

**Comment by delashum** [comment]
Yeah, that's a reasonable request. I personally use checkboxes all over for temporary things that I don't want to show up, so that's why I required the tag. I will make it so that you can leave it blank to scan all lines in a future update.

**Comment by Gnopps** [comment]
Great stuff, thank you!

**Comment by inakarmacoma** [comment]
Just wanted to +1 the feature request. I don't think I'll be able to use the plug-in with the tag requirement; perhaps the value could be inferred from the Page title, or the Header title, or similar? Just an idea. Thanks!

**Comment by happy15** [comment]
maybe it could be generalized to match prefix of hash specified by user.

if none prefix is specified, then all checkboxes are matched.

I just thought about similar idea this morning and found that you already did it. 👏

**Comment by mikeriss** [comment]
+1 for this feature. My system is as follows: I have todos without any hashtag which I would like to show up. Then when I plan my day I turn those todos as #today #upcoming #later #waiting

**Comment by technovangelist** [comment]
i would also like to have it without tags, but then for some use tags and show those as well.

**Comment by sebastianfastert** [comment]
Great ideas. In my opinion it would be great, if could just add the todo tag to the [yaml front matter](https://publish.obsidian.md/help/Advanced+topics/YAML+front+matter) and all todos from that page are added to the checklist.
Thank you very much. I love this plugin 👍

**Comment by delashum** [comment]
This is the next ticket I'll work on, probably this weekend. I didn't know about the yaml front matter concept until now. Of the ideas I've heard so far, that's my favorite and probably how I will implement it unless there are any objections.

**Comment by delashum** [comment]
I think that's reasonable. My current plan is to allow you to set the tag in settings to empty which will scan every todo in every file. Or if you do specify a tag in settings, then you could set a tag on a page level via `yaml front matter`

**Comment by inakarmacoma** [comment]
> allow you to set the tag in settings to empty which will scan every todo in every file. 

That makes a lot of sense to me. One idea to consider would be to include a check-box indicating what element should be used above the tasks. For example, it could say:

**Tag: [         BLANK            ]
Task title: [ ] Page title, [ ] Above header, [ ] Above bold text, [ ] Above non-task parent node**

> Or if you do specify a tag in settings, then you could set a tag on a page level via `yaml front matter`

Seems logical. I think the thing to avoid would be requiring that everyone add yaml front matter to every page as a prerequisite. More of an 'as-needed' basis. Might need to let user to specify which overrides the other? Unless there's an obvious natural default.

**Comment by delashum** [comment]
I just released `1.1.0` which adds two features. You can now leave the Todo tag setting empty, which will parse every file. You can also add the todo tag to the front matter YAML which will parse all checklists in that file regardless of if they're tagged or not.
