### ISSUE TITLE
Checklist not rendering any items after upgrading to 2.2+

### ISSUE THREAD

**Issue by chrisgmbishop** [delashum/obsidian-checklist-plugin#142]
Hey @chrisgmbishop I'm going to close this issue as based on some other comments people have left the original issue described here has been fixed.

If you are continuing to face issues could you please open a new issue with as much details as you can give on the problem. Preferably including obsidian version, checklist version, your hardware, and screenshots if possible. Thank you!

_Originally posted by @flankstaek in https://github.com/delashum/obsidian-checklist-plugin/issues/139#issuecomment-1190280225_

I'm on Obsidian 0.15.6
Checklist 2.2.3
Macbook Pro M1Pro

**Comment by chrisgmbishop** [comment]
What is showing:
![Screen Shot 2022-07-20 at 17 59 47](https://user-images.githubusercontent.com/16527614/180076044-c2e1e020-0ea4-47bd-bb44-dfd8d95ba048.png)

My typical Task block:
![Screen Shot 2022-07-20 at 18 00 31](https://user-images.githubusercontent.com/16527614/180076094-64e89dda-8225-45e1-b2ea-ddedf1373db3.png)

My Settings:
![Screen Shot 2022-07-20 at 18 00 52](https://user-images.githubusercontent.com/16527614/180076125-b301b14b-cf88-47fd-be3f-03cc023b9537.png)

**Comment by chrisgmbishop** [comment]
I have many other open tasks in other files that used to render here and are now no longer

**Comment by flankstaek** [comment]
Would you mind sharing the exact list of tags you are sorting for (copy your whole list and paste here)?

In addition, the items shown in your screenshot would not show up in this example as you have "Show Completed" unchecked and are only showing a completed task & an empty task. A task with no body will not show up in the sidebar.

**Comment by chrisgmbishop** [comment]
> Would you mind sharing the exact list of tags you are sorting for (copy your whole list and paste here)?
> 
> 
> 
> In addition, the items shown in your screenshot would not show up in this example as you have "Show Completed" unchecked and are only showing a completed task & an empty task. A task with no body will not show up in the sidebar.

Sorry, below the OP I note that I have plenty of other notes with incomplete tasks that have a body that previously showed.

I have tested for an overactive 'show Completed' by switching the setting and had no difference.

The initial tags I had were
task
tasks

And have since tried accounting for case sensitivity and added two more. So the list is:
task
tasks
Task
Tasks

Thanks

**Comment by flankstaek** [comment]
I'm not able to replicate this behavior. In addition the tag name shouldn't be case sensitive.

I can see in the pane that it's not loading all of your included tags though as the output is only listing "#task #task" and none of your other included tags, so if you wouldn't mind downloading the latest update & trying to re-enter your tags after deleting all text in the included tags box. After resetting the window please try reloading the app and confirming it's still not working.

If it still isn't working would you be able to open the dev console (Command+Option+J) and modify some tasks and see if any errors are output. Thank you!

**Comment by chrisgmbishop** [comment]
No luck after attempting those measures.
I've copied what I've found in the Dev console. Looks like an issue with the parameter going into .toLowerCase
![Screen Shot 2022-07-22 at 10 44 59](https://user-images.githubusercontent.com/16527614/180447090-d1098dd0-12cc-46ab-9653-d7c5f2f7cf5b.png)

And the resulting location in the JS
![Screen Shot 2022-07-22 at 10 44 15](https://user-images.githubusercontent.com/16527614/180447122-f401e043-fc77-4234-9069-4cf6fde29b37.png)

Does this help?

**Comment by flankstaek** [comment]
That does help - it appears as though you might have some malformed tags present, or at least tags that the plugin was not handling correctly.

I've added an attempted fix, try the latest release and let me know if it fixes it.

**Comment by chrisgmbishop** [comment]
First thank you for your time on this.

I was getting no errors after updating and wiping and readding the tags
I decided to qipe the slate clean. I uninstalled the plugin, reinstalled and am now getting a different error once I've set everything back up the way it was:
![Screen Shot 2022-07-22 at 13 55 57](https://user-images.githubusercontent.com/16527614/180483289-eb457cd3-07b3-4de1-95df-8ee5b11a4cab.png)

And:
![Screen Shot 2022-07-22 at 13 56 36](https://user-images.githubusercontent.com/16527614/180483321-823930ad-87c1-4710-b050-7044cc949226.png)

**Comment by tristancade** [comment]
Having the same issue. Purely observational, but it seems that the issue starts once you get past a certain number of list items for a particular tag (maybe 15ish entries or so.)

**Comment by flyingbirdhub** [comment]
> First thank you for your time on this.
> 
> I was getting no errors after updating and wiping and readding the tags I decided to qipe the slate clean. I uninstalled the plugin, reinstalled and am now getting a different error once I've set everything back up the way it was: ![Screen Shot 2022-07-22 at 13 55 57](https://user-images.githubusercontent.com/16527614/180483289-eb457cd3-07b3-4de1-95df-8ee5b11a4cab.png)
> 
> And: ![Screen Shot 2022-07-22 at 13 56 36](https://user-images.githubusercontent.com/16527614/180483321-823930ad-87c1-4710-b050-7044cc949226.png)

i submit a PR: https://github.com/delashum/obsidian-checklist-plugin/pull/145, for this problem, it may be solved by this PR.

**Comment by chrisgmbishop** [comment]
> Having the same issue. Purely observational, but it seems that the issue starts once you get past a certain number of list items for a particular tag (maybe 15ish entries or so.)

I can confirm, I definitely have more than 15 entries

**Comment by flyingbirdhub** [comment]
> > Having the same issue. Purely observational, but it seems that the issue starts once you get past a certain number of list items for a particular tag (maybe 15ish entries or so.)
> 
> I can confirm, I definitely have more than 15 entries

the problem you describe may be is different. the solved bug is not caused by number of todo entries, just because of some embed inline images. you can try it

**Comment by llathieyre** [comment]
I have the same issue, none of my tasks are rendered anymore.
I can't pinpoint to a specific event (may be a plugin upgrade)

Checklist 2.2.5
Obsidian 0.15.9 (installer 0.15.8)
MacOS

**Comment by vilcansu** [comment]
Having the same issue.

Obsidian Version 0.15.9 (installer 0.15.9)
Checklist 2.2.5
macOS Monterey.

P.S. I love the plugin and many thanks for creation and maintenance!
![Screenshot 2022-08-03 at 09 49 52](https://user-images.githubusercontent.com/6813608/182553842-3713b326-6867-42a3-96ad-d0a678335c57.png)

**Comment by kevindantoine** [comment]
Hi, all. I'm having the same issue. No checklists are being rendered. Are there any fixes? First, the "#todo" broke for me and I started using "#td", I made some changes to sliding panes just a few minutes ago and my checklists are no longer available. The same issue as the first "#todo" break: "No checklists found for tags: #td #todo"

**Comment by tristancade** [comment]
@kevindantoine yep yep, @flyingbirdhub had the fix. Thank you btw! 😀 As soon as I removed inline embeds from the lists, they were selectable again with all items showing up.

**Comment by kevindantoine** [comment]
> @kevindantoine yep yep, @flyingbirdhub had the fix. Thank you btw! 😀 As soon as I removed inline embeds from the lists, they were selectable again with all items showing up.

I removed mine and no tags are working, reinstalled and still no luck :(

**Comment by flankstaek** [comment]
Appreciate everyone's feedback - I've merged the code from @flyingbirdhub. Please update versions and see if that fixes it.

**Comment by kevindantoine** [comment]
> Appreciate everyone's feedback - I've merged the code from @flyingbirdhub. Please update versions and see if that fixes it.

Updated, still no luck on my end.

**Comment by llathieyre** [comment]
a []() link works
a [[]] internal link breaks it

**Comment by kevindantoine** [comment]
> a []() link works a [[]] internal link breaks it

Thank you! I ended up doing a vault search and removed all my backlinks, pdfs and other embedded files as well as brackets and I am happy to announce that it is WORKING! 

You only know what you have when it's gone! Where can I tip the active devs??

**Comment by flankstaek** [comment]
Sorry just to confirm - internal links in the todo are breaking?

**Comment by llathieyre** [comment]
yes
Laurent Lathieyre <http://www.linkedin.com/in/llathieyre> {he|him} |
***@***.*** | (425) 229-7272 | Seattle, WA

**Comment by flankstaek** [comment]
Thank you! Got it, embedded links are 100% causing failures. As for active devs these days it's primarily just me maintaining the plugin.

I will work on getting a fix for inline embeds during the week - if anyone has any OTHER issues please create a new issue detailing the problem as detailed as possible.

**Comment by flankstaek** [comment]
Actually I was able to figure out what was still causing the issue - you can have inline embedded links in your todolist now. Please update and let me know if that fixes it.

**Comment by chrisgmbishop** [comment]
Latest upgrade nuked my bug as well. Awesome work! thank you for this stellar plugin.
