### ISSUE TITLE
[Feature request] merge list item and checkbox after pasting the code

### ISSUE THREAD

**Issue by igorwojda** [delashum/obsidian-checklist-plugin#144]
See this video
![2022-07-26_14-29-15 (2)](https://user-images.githubusercontent.com/530122/181006639-57e8a47c-d890-4d69-9840-e37453faeec7.gif)

Result
<img width="133" alt="image" src="https://user-images.githubusercontent.com/530122/181006684-65a31052-1933-469b-8838-dfd7ee41f09e.png">

Expected result
<img width="145" alt="image" src="https://user-images.githubusercontent.com/530122/181006744-ba6778ea-363f-44ce-bb83-8237bcb144cf.png">

**Comment by flankstaek** [comment]
This isn't really in the scope of this plugin - this is happening in the obsidian editor not the plugin.
