### ISSUE TITLE
Careful with the spaces!! (not rendering items) 

### ISSUE THREAD

**Issue by ser97gio** [delashum/obsidian-checklist-plugin#147]
Hello
Thank you for this great plugin.
I had an issue with the rendering of the items, i thought it was because of the embedded links. So i fixed that, but it did not work.
to the point, my mistake was this: i had a [[Wikilink]] tiped like this [[Wikilink ]], with an space at the end. I deleted the space and the lists redered like magic. 
I don't know if it is a bug, but it breaks de plugin
I hope it is useful to somebody. 
(disclaimer: i am not a native speaker)
(by the way, how do i tag this topic as a bug?)

**Comment by jluna79** [comment]
Thank you for sharing!

I did find this problem with one of my links, however, after fixing it, I still get a _"No checklists found for tag: `todo`"_ message. I'm still trying to fix this.

p.s In case it helps, if anyone affected is not familiar with regexp, a fast way to find which link is causing this problem is to search (Cmd+Shift+F) for:

`/\[\[ /` or `/ \]\]/`

**Comment by huyz** [comment]
OMG this was the reason? One space in an internal link breaks the entire plugin? I had no idea and would have never figured that out. This is definitely a showstopper bug.

> /\[\[ / or / \]\]/
Btw this `OR` needs to be capitalized.
And you'll get a lot of bad hits if you have a lot of shell script code :)

**Comment by jluna79** [comment]
I did found a link with this problem but, as stated before, after removing the white space I still can't get the items to appear.

I still get a message that reads:
> No checklists found for tag: `todo`

I haven't found a solution yet.

**Comment by jluna79** [comment]
Follow up, I did find a way to replicate the bug with the trailing spaces (not the bug that I have with my tags, though :( )

Here's an image of the bug in action:

<img width="1002" alt="image" src="https://user-images.githubusercontent.com/411374/184341352-edf8f083-7b71-480b-be9f-9e843b2a42f4.png">

**Comment by flankstaek** [comment]
Hey - I've fixed the spaces issue, it'll be in the next release (adding a few more bugs in there). Can you go ahead and open a separate issue with your tag problem? Preferably with some more details of what's causing it to occur if you can.

In addition if you can open the Developer Console and screenshot any errors that will help me debug.
