### ISSUE TITLE
[Feature] `Open view` doesn't show the pane

### ISSUE THREAD

**Issue by huyz** [delashum/obsidian-checklist-plugin#149]
If the checklist view is already opened somewhere, running the command `Open view` doesn't show it if another tab is selected in the sidebar. In other words, it only opens a view but doesn't unhide it if necessary.

Ideally, it would act like `Show tag pane` (and also be renamed to use the same verb `Show` for consistency), which both makes sure that the view is opened somewhere and it is unhidden if there are other tabs in that group of views.  Similarly, it should be idempotent (running the command again shouldn't hide it).

**Comment by flankstaek** [comment]
Done - thanks for the suggestion :)

**Comment by huyz** [comment]
Perfect, nice!
