### ISSUE TITLE
Make only checkbox clickable

### ISSUE THREAD

**Issue by Gnopps** [delashum/obsidian-checklist-plugin#15]
I've noticed that I sometimes by mistake tick a checkbox in the plugin window, when I am trying to click something else or scroll the window (using touch). Would it be possible to tick the checkbox in the plugin only when you click the checkbox itself?

**Comment by mabiga** [comment]
Good Idea. I would like that as well. Furthermore, you could make the rest of the line a link to open the note where the task sits. I usually have some context before/after my tasks and that would make navigating really easy.

**Comment by delashum** [comment]
Yeah, this is a good idea. Will do it
