### ISSUE TITLE
Checklist track failed for the tasks in Obsidian callouts?

### ISSUE THREAD

**Issue by gavinwoo007** [delashum/obsidian-checklist-plugin#160]
The tasks I created in the Obsidian callouts can't be traced by the checklist, but Checklist can track the tasks in Obsidian Admonition, any idea to fix it?

**Comment by gavinwoo007** [comment]
Hi, after I updated the latest checklist plugin, I can add todo in the callouts, but the todo status can't be synchronized.
![image](https://user-images.githubusercontent.com/97218731/207759672-cf14c1fd-c46c-4c53-824f-71bb244edd3c.png)
![image](https://user-images.githubusercontent.com/97218731/207759926-0c0d5317-800d-4d44-be5b-5cb77e48d5ba.png)

**Comment by flankstaek** [comment]
Should be fixed in the latest update!

**Comment by gavinwoo007** [comment]
Thanks! it works perfectly!
