### ISSUE TITLE
Proper way to use .css snippets for obsidian-checklist-plugin.

### ISSUE THREAD

**Issue by cococodeng** [delashum/obsidian-checklist-plugin#162]
I want to make fonts looks smaller for this extension, but i don't want to touch default .css config.

Is there a proper way to override extension settings by enabling css user stype in "CSS Snippets"?

Any examples for modifying font size for this extension?

**Comment by flankstaek** [comment]
If you press Ctrl + Shift + I on windows or Cmd + Shift + I on a mac you should be able to open the inspector and hover over different elements to help figuring out CSS snippets. You can also edit CSS inline from that window to test your code.

If you wanted a snippet targeting specifically the task text size you could try something like:
```css
.checklist-plugin-main .content p {
  font-size: 16px
}
```

Which should set the default font size for the todo to 16, let me know if you need additional info.
