### ISSUE TITLE
Feature Request: Support the Tasks Plugin

### ISSUE THREAD

**Issue by taurr** [delashum/obsidian-checklist-plugin#165]
I use the [Tasks](https://github.com/obsidian-tasks-group/obsidian-tasks) plugin in combination with the Checklist plugin.

However, completing a task using the Checklist sidebar, doesn't let Tasks put in the completed date information. This means I have to click the task in the sidebar just to go to the note that holds the task, then complete it normally, just to go back where I left.

It would really help if there was some kind of coop between the 2 plugins.

**Comment by Erik-Handeland** [comment]
Curious if you've tried using Tasks query for say:
\```tasks
not done
due today
\```

And drag that note the side bar?

<img width="660" alt="image" src="https://user-images.githubusercontent.com/16601367/230031368-85786573-c64f-4a1b-b559-583a324f3e79.png">
* Ignore the green background working through a CSS margin issue

**Comment by taurr** [comment]
Nope... hadn't thought of that one 😄 
It does solve the issue - unfortunately for this addon, it won't be required then..

Now off, and create an issue with the suggested query... if checking repeated items through it, it doesn't repeat...
