### ISSUE TITLE
Color on Discordian theme

### ISSUE THREAD

**Issue by Tweetyblue** [delashum/obsidian-checklist-plugin#18]
Hi,

The todo list apears with white text on light grey background on Discordian theme. Is it possible to ajust the colors to the theme, please ?

**Comment by delashum** [comment]
I exclusively use the css color variables for all of the colors in this plugin, so if the colors aren't showing up correctly I'm not sure what else I can do to support that. Do you have a suggestion?

**Comment by Tweetyblue** [comment]
Thank you for your answer. I don't know what could solve it, I'm not familiar with coding.

**Comment by delashum** [comment]
`1.2.1` exposes a custom set of CSS variables which gives you full control over esthetic. closing this
