### ISSUE TITLE
Stopped working

### ISSUE THREAD

**Issue by lethefrost** [delashum/obsidian-checklist-plugin#181]
Showing only `No checklists found for tag: ...` in the panel. It used to work in the past. Now it breaks with Obsidian v1.4.2 and Checklist v2.2.12

**Comment by darylchc** [comment]
Hi there, I'm having the same issue here since updating to ver 1.3.7. 
This plugin is the best that I've used for todo lists in Obsidian. Hope this gets fixed. 
Thanks for the work that you do.

Best,

Daryl

**Comment by afterfits** [comment]
I have the same issue on v1.3.14. Would be so grateful if this gets fixed!

**Comment by AldenB0** [comment]
I'm also dealing with this issue and after some messing around, it only seems to break when I add a preexisting tag (a tag with multiple lists already under it) in the tag name section. If I remove all of my preexisting tags from the list and populate it with new unused tags everything works fine. but once I add a preexisting tag to the list everything breaks including the other tags. 
Hopefully, this can be fixed soon and thanks for making such a great plugin!

**Comment by delashum** [comment]
Are there any errors in the console?

**Comment by delashum** [comment]
Maybe fixed in 2.2.13; let me know.

**Comment by AldenB0** [comment]
> Maybe fixed in 2.2.13; let me know.

The update fixed the issue! Thanks for letting me know there were changes.

**Comment by Loberation** [comment]
@delashum I guess you could close this issue?
