### ISSUE TITLE
Several checkboxes on a same task line

### ISSUE THREAD

**Issue by Tweetyblue** [delashum/obsidian-checklist-plugin#19]
Hi, is it possible to have several checkboxes on a same task line under the todo list, please ?

**Comment by delashum** [comment]
I'm not sure what you mean by this, can you give me an example?

**Comment by Tweetyblue** [comment]
I mean, grouping several checkboxes on the same line on your checklist instead of one by line.

I am also interested in changing the font size of the checklist.

**Comment by delashum** [comment]
Do you mean nested items? If you could type an example of the markdown file, and how you'd like it to show up that would be very helpful

**Comment by Tweetyblue** [comment]
It is impossible to markdown several functional checkboxes on the same line, but maybe it could be possible to group them in the check list. To save place when you have a lot of checkboxes. Something like this :

https://nsa40.casimages.com/img/2021/02/22//210222081732504657.jpg

**Comment by delashum** [comment]
`1.2.1` exposes a set of CSS variables, so you can customize font size now. Not planning on supporting multiple checkboxes on a single line. closing
