### ISSUE TITLE
Plugin cannot handle points in the note name

### ISSUE THREAD

**Issue by monnypython** [delashum/obsidian-checklist-plugin#2]
> Great idea. In my case very helpful to keep an eye on todos over a lot of daily notes.

1. I use the standard plug-in for daily notes. I use the german standard format for the date: 02.22.2021 (DD.MM.YYYY). The plugin basically doesn't seem to be able to handle dots in the note name.
As can be seen in the picture, these notes are sorted as "undefined".

It is possible to fix that?

![obsidian_ListPlugin](https://user-images.githubusercontent.com/42573701/105478313-53c86a00-5ca3-11eb-9687-ddb508ecb6b6.png)

2. I think the tag in list is redundant and not necessary (for me).
There might be an option to toggle the tag on and off in the sidebar.

**Comment by delashum** [comment]
I will definitely get no.1 fixed.

With no.2 you don't actually have to tag each todo item you just tag a block and it will pick up all todo's in that block. That being said I think it's a good idea to strip the match tag out out of the checklist when rendering. I'll include that in next release as well.

**Comment by monnypython** [comment]
Sounds greate.
Thank you!
