### ISSUE TITLE
Render todo items as checkboxes instead of the radio button look

### ISSUE THREAD

**Issue by despens** [delashum/obsidian-checklist-plugin#23]
At the moment, the checklist plugin renders checkboxes looking like radio buttons, as if from a list of items it was possible to pick only one. It would be great if the plugin would follow the standard and use a checkbox visual.

**Comment by delashum** [comment]
I personally like the look. I modeled it after iOS Reminders which also use the circular toggle aesthetic.  Unless I hear a lot of complaints about the look I'm going to stick with it for now. I may release optional themes in the future that could include that look. If so I'll update this issue.
