### ISSUE TITLE
Missing commands and keybindings

### ISSUE THREAD

**Issue by lyndhurst** [delashum/obsidian-checklist-plugin#24]
Hi, thanks for making this plugin, it is a nice addition to Obsidian.

I have been looking around for a command from the palette, or keybindings in the menu, and cannot find anything related to your plugin. Am I missing something?

I do not think many commands or keybindings are needed, but at least being able to open the task list would be nice (I personally prefer to open it in a pane rather than the sidebar, but either way...), so far the only way I found to get the task list back after closing a pane, is to disable and re-enable the plugin from settings.

Also, being able to toggle the file / tag grouping strategy while looking at the list could be useful I think.

Thanks for your time.

**Comment by delashum** [comment]
Yes, this is a good idea. Will include in a future release
