### ISSUE TITLE
Allow for a single empty space between the tag and the checklists

### ISSUE THREAD

**Issue by timothyjlaurent** [delashum/obsidian-checklist-plugin#26]
I recently installed the Prettier plugin - I love how it standardizes the formatting of the MD. One thing it does however, is put a blank line after every `\n` so my todos changes from:

```markdown
#todo
- [ ] eat the rich
```

to: 

```markdown
#todo

- [ ] eat the rich
```

This breaks the sidebar 😭  tasks.

I wish we could use both this plugin _and_ the Prettier plugin.

**Comment by delashum** [comment]
Hmm, this is interesting. I suppose I could change it to ignore all empty lines after a tag until it reaches some content. I'll include that in a future release

**Comment by delashum** [comment]
fixed in `1.2.0`

**Comment by timothyjlaurent** [comment]
great this works, thanks for adding it.
