### ISSUE TITLE
Copy the plain text of aggregated tasks

### ISSUE THREAD

**Issue by yinguohang** [delashum/obsidian-checklist-plugin#27]
First of all, thank you for bring this marvellous plugin!

Is that possible to copy the aggregated todo list so that I can note it down somewhere in the vault?

**Comment by delashum** [comment]
Do you mean you would like a copy button that would just copy a plain text list of all the todos?

**Comment by yinguohang** [comment]
Thanks for your reply! Yeah, I think that sounds helpful to me since I can have a summary for current todo items.

**Comment by delashum** [comment]
I think this is a pretty fringe use case, closing until that changes
