### ISSUE TITLE
Would you accept PRs for any of the following?

### ISSUE THREAD

**Issue by krivaten** [delashum/obsidian-checklist-plugin#29]
First of all, thank you for this plugin. This is almost exactly what I was already planning on building to replace my use of Todoist and it works _really_ well.

I was wondering if you would accept PRs for any of the following:

1. Some updates to the HTML output to make it follow a more semantic and accessible structure (It's one of the areas I specialize in). Taking a cursory glance, I'm thinking something like the following, with styles to fix any layout issues that result.
```html
<section class="group">
    <header class="group-header tag svelte-im5pnh">
        <button class="title svelte-im5pnh"><span class="tag-base svelte-im5pnh">#todo/</span></button>
        <div class="space svelte-im5pnh"></div>
        <div class="count svelte-im5pnh">12</div>
        <button class="collapse svelte-im5pnh">
            <svg focusable="false" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 512" class="svg down svelte-t9i4te"></svg>
        </button>
    </header>
    <ul class="group-list">
        <li class="item compact svelte-zpfope">
            <div class="toggle svelte-zpfope">
                <div class="checkbox svelte-y3iyim"><div class="svelte-y3iyim"></div></div>
            </div>
            <div class="content svelte-zpfope"><span>Reading chair</span></div>
        </li>
    </ul>
</section>

```
2. Adding a class to the `.group` with the group's name (e.g., `#todo/MyResearch` would add `my-research` as a class name). This would allow folks to add custom CSS if, for example, they wanted to theme specific groups in their custom CSS.
3. Using custom properties/variables for more of the CSS (e.g., size of the box) so that they are more easily customizable.
4. Adding new tasks directly from the sidebar. I know this would likely require some discussion as to _how_ to tackle this for items grouped by tag, but I imagine it should be possible without too much effort.

**Comment by delashum** [comment]
Yes, definitely. Especially on the first 3, as I will admit that is not my forte. For #4 I would love to have some more discussion around requirements and how this would work before it's implemented.

**Comment by delashum** [comment]
Does any of those 3 relate to #13 , as I am not sure what needs to happen to allow people to customize things like that, and would love any guidance.

**Comment by krivaten** [comment]
Awesome! As for your question, yes it could definitely address that request. So instead of requiring someone to drill in to the CSS classes they could just set something like:

```css
:root {
    --Checklist-fontSize: 20px
}
```

Then in the CSS for the plugin you could do something like:
```css
.content {
    font-size: var(--Checklist-fontSize, inherit);
}
```

The second argument (i.e., "inherit") is the fallback if the `--Checklist-fontSize` variable is not defined.

I can try to hack on this a bit over the next few days and get something to you for your review.

**Comment by krivaten** [comment]
Oh, and as for no. 4, yeah we can definitely chat about that. I will need to dig in to the code a bit more before I can give much input on it though.

**Comment by krivaten** [comment]
So it took longer to get around to this than I had hoped, but it's not letting me create a PR from my fork. Is that a permission you need to enable on your end, or just something I am missing on my end?

**Comment by delashum** [comment]
Hmm, I'm not sure. I did a quick google search and doesn't look there is anything I need to enable. Do you not see the PR button as described in this [article](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request)?
