### ISSUE TITLE
Plugin doesn't find todos

### ISSUE THREAD

**Issue by lillianhorin** [delashum/obsidian-checklist-plugin#31]
I have just installed the plugin but it isn't able to find any of the todos. I've tried changing the tag, editing the pages, making new pages, and uninstalling and reinstalling. Still for some reason it can't find any of the checklists.

**OS**: Windows 10
**Obsidian Version**: v.0.11.5
**Plugin Version**: v.1.0.13

Here are my settings for the plugin.
![image](https://user-images.githubusercontent.com/24489520/112576011-d1a21200-8dc7-11eb-88d5-22dbbb00b577.png)

Here is an example of a checklist that isn't getting identified by the plugin.
![image](https://user-images.githubusercontent.com/24489520/112576051-e4b4e200-8dc7-11eb-8ab5-91787c9f424e.png)

Thank you!

**Comment by ericaxu** [comment]
Make sure there isn't an empty line between the tag and the checklist. That should fix it.

**Comment by lillianhorin** [comment]
> 
> 
> Make sure there isn't an empty line between the tag and the checklist. That should fix it.

That fixed it, thank you! 

If there are any plans to have a non-hashtag related system (i.e. scanning entire notes) I would be all for it. I usually group my to-dos into different categories within each day or project (as seen in the image below) so the hashtag needing to be right above the checklist is a bit strange. If there's a way around needing to write the hashtag directly above the checklist as it is now I'd love to hear it. 

![image](https://user-images.githubusercontent.com/24489520/112708961-d4fed180-8e8b-11eb-9929-e3112e93f285.png)

Thanks so much for development on the app! This particular plugin is pretty essential for me so I'm excited to get it going.

**Comment by delashum** [comment]
@ericaxu is correct. Please track #14 for progress on global tags
