### ISSUE TITLE
Possible To Add Support For Tasks on Lines Starting With "*"?

### ISSUE THREAD

**Issue by pingviini42** [delashum/obsidian-checklist-plugin#32]
The majority of my notes have unordered lists denoted by asterisks instead of dashes. Would it be possible to support tasks on lines denoted as such?

Thanks for such a great plugin!

**Comment by delashum** [comment]
Yeah I can do that. I wasn't aware that was a format that was used for checklists. Should be an easy add

**Comment by delashum** [comment]
fixed in `1.2.0`
