### ISSUE TITLE
Properly render external markdown links

### ISSUE THREAD

**Issue by lillianhorin** [delashum/obsidian-checklist-plugin#34]
Thanks so much for this plugin. Even the latest update has completely changed the game for me and now Obsidian is much more usable for me as a project manager.

I have a lot of external links in my to-dos but they aren't being rendered as links in the checklist. I see the Markdown code for the link instead. It takes up a lot of space so it'd be great if it could be shown as a link like in the documents!

Thanks!

The links in the checklist plugin 
![image](https://user-images.githubusercontent.com/24489520/112773164-edddc300-9002-11eb-957d-871a100357a4.png)

The links in the document
![image](https://user-images.githubusercontent.com/24489520/112773141-d7d00280-9002-11eb-979f-410f7c7c471d.png)

**Comment by delashum** [comment]
Yeah, definitely need to add support for this.

**Comment by delashum** [comment]
fixed in `1.2.0`
