### ISSUE TITLE
Tag sections

### ISSUE THREAD

**Issue by sagikazarmark** [delashum/obsidian-checklist-plugin#38]
#14 added support for tags in the front-matter which is great, but that loads tasks from the whole page.

It would be nice to scan only a section marked by a header. For example:

```markdown
# My day

## Schedule
- [ ] 08:00 Meeting with Peter
- [ ] 09:00 Work
- [ ] 18:00 Go home (actually, you already are :) )

## Tasks #todo
- [ ] Todo A
- [ ] Todo B
- [ ] Todo C

## For tomorrow
Collect the tasks for tomorrow here:

- [ ] Todo A
- [ ] Todo B
- [ ] Todo C
```

In this example I'd only want items under `## Tasks` to show up in the checklist. Do you think it's possible to implement?

**Comment by delashum** [comment]
Yes, that is exactly how this plugin works. Look at the readme in this repo. You just need to remove the tag from frontmatter for that page as well

**Comment by sagikazarmark** [comment]
Oh, great! I've actually tried that a couple times, but didn't work. I upgraded Obsidian and all plugins now and it seems to work. Thanks and sorry for the noise!
