### ISSUE TITLE
Is it possible to set up GitHub sponsor?

### ISSUE THREAD

**Issue by ericaxu** [delashum/obsidian-checklist-plugin#39]
Tried reach out to @delashum on Discord but it seems Jacob is not active there, so I'll ask instead.

Depends on where you live it might be tricky or even impossible to set up GitHub sponsor. But if it's something you don't mind doing, I would really appreciate it. Thanks!

**Comment by delashum** [comment]
I just joined the discord server at as `@delashum`. Lets talk there
