### ISSUE TITLE
Group headers missing

### ISSUE THREAD

**Issue by Gnopps** [delashum/obsidian-checklist-plugin#40]
It seems like since the last update (?) that group headers are missing. This is what the plugin window looks for me with no theme applied:

![image](https://user-images.githubusercontent.com/16313148/112951602-3224ac80-9144-11eb-9dde-4a75495481ef.png)

I've set the plugin to group by page.

**Comment by delashum** [comment]
Do you have a tag set? If you have no tag set then it no longer shows the groups because it doesn't have enough information to be able to.

**Comment by Gnopps** [comment]
Thanks for your answer. I thought (perhaps incorrectly) that the page name used to be shown.

**Comment by delashum** [comment]
Oh, yes this is a mistake on my end. I will push a fix soon. I stripped it out only thinking about sub-tag grouping, and totally forgot about page grouping. Sorry about that

**Comment by delashum** [comment]
fixed in `1.2.0`
