### ISSUE TITLE
Showing todo in multiple groups (when grouping by tag)

### ISSUE THREAD

**Issue by tgenman** [delashum/obsidian-checklist-plugin#44]
First of all, thank you for cool plugin.

I hope this suggestion which can be useful.

For example note is a project. There are list of todo for longterm planning. I want to see these todo in plugin and because of that I added #todo/pool in head. But also I plan finish one of todos today and add special tag for seeing it in list of today tasks #todo/today.
```
#### #todo/pool
- [ ]  📎 Title 1 #todo/today 
- [ ]  📎 Title 2
- [ ]  📎 Title 3
```

In this case todo Title 1 will shown only in #todo/pool section. 

Could you please add showing it in both sections ?

**Comment by delashum** [comment]
Yeah I run a de-dupe on all tasks (by line number by file) before displaying. I guess it makes sense to have things appear in multiple groups. Will include in next release
