### ISSUE TITLE
Checkboxes of multiline to do's don't align

### ISSUE THREAD

**Issue by janpeeters70** [delashum/obsidian-checklist-plugin#46]
I noticed that checkboxes of multiline to do's don't align with the single line ones. 
I know it's a minor thing so see if it's viable to fix.
![Screencapture 2021-04-16 at 08 55 51@2x](https://user-images.githubusercontent.com/4502360/114984950-8644c600-9e92-11eb-98d5-d3a6eb9b0477.png)

Sorry this seems to be an issue with my theme California Coast, Minimal Theme shows the checkboxes alright.

**Comment by delashum** [comment]
yeah i can fix that one. will tag it on the next release

**Comment by delashum** [comment]
I installed that california coast theme and am not able to reproduce the misaligned check boxes. Is it possible you have some custom CSS that is interfering?

**Comment by janpeeters70** [comment]
Hi @delashum,

Thanks for looking at this issue. It has to do with a fault in the CC theme and had been fixed in the meantime by the author of that theme.

Best, Jan
