### ISSUE TITLE
win10 link from task problem

### ISSUE THREAD

**Issue by DannyDies** [delashum/obsidian-checklist-plugin#47]
Hey! It's me again, with a new issue :D On windows, when I use link from task, I get a message from windows like on screen. The link opens in the background properly, but this window kinda annoying. 
p.s. reinstalling the plugin and resetting the css didn't help
![win_issu](https://user-images.githubusercontent.com/70198933/115961599-c43f8b00-a51f-11eb-8635-5a82d315d6d1.png)

**Comment by delashum** [comment]
Hmm, this is interesting. I don't work on a windows machine, so difficult to repro on my end. I have a hunch of what might work which I can include in the next release though

**Comment by DannyDies** [comment]
Thank you. After update, I'll write here about the result
