### ISSUE TITLE
installed version 1.2.1 but checklist keeps loading, bug? 

### ISSUE THREAD

**Issue by SehYang** [delashum/obsidian-checklist-plugin#48]
Hi, I just installed the plugin but it just keeps spinning, and I’m using the 1.2.1 version, hopefully it can be fixed, 
this is what I did and the console showed:

![](https://cdn.discordapp.com/attachments/709961842440798319/835847188906639390/unknown.png)

![](https://cdn.discordapp.com/attachments/709961842440798319/835847239250739230/unknown.png)

thank you in advance 😄

**Comment by delashum** [comment]
I will include a fix in the next release.

**Comment by SehYang** [comment]
thank you, will update with the result 😄

**Comment by delashum** [comment]
fixed in `1.2.2`

**Comment by SehYang** [comment]
the update fixed it and its working now, thanks!
