### ISSUE TITLE
[idea] Have the ability to have multible tags as lists

### ISSUE THREAD

**Issue by LFGaming** [delashum/obsidian-checklist-plugin#49]
I think it would be nice to have the ability to chose multible tags for the list, so i can have `#todo` but also have `#ideas` for example. Probably seperated by a `,` in the settings, or with some other way. I think this will make me use the plugin much more.
But for the rest is it an awesome plugin. :)

Just found out about the grouping, so I can now do what i wanted, but I still think that adding my idea from above would be nice.

**Comment by delashum** [comment]
Yeah, this is a reasonable request. Will include in next release

**Comment by BurritoAssassin** [comment]
Yes yes and yes to this enhancement.

The sidebar needs a switcher element (e.g. dropdown menu) to change the task list currently shown, and needs an option to show "All Tasks" across all lists.

The config section can use a comma to separate list hashtags, chips (if it's an available UI component), a multi-line text field, etc.
