### ISSUE TITLE
Filter todo list by tag

### ISSUE THREAD

**Issue by antonioargentieri** [delashum/obsidian-checklist-plugin#5]
Love the plugin, thanks for putting it together.

One thing that I would love to see is the ability to filter the list by tag. 
This would involve allowing multiple tags to be used for todo's and perhaps using a drop down list to filter a specific tag.

I manage multiple projects using Obsidian and need to switch between them quickly.
Being able to quickly view a specific list of outstanding todo's for a specific project would be a real time saver.

**Comment by delashum** [comment]
Yes definitely. I feel this pain as well. i'm working on a fix for this
