### ISSUE TITLE
Loading forever

### ISSUE THREAD

**Issue by jshum** [delashum/obsidian-checklist-plugin#50]
Getting a bug in the checklist plugin where it keeps spinning and the tab never loads.

I disabled all plugins except the checklist one, and the error in the dev console is `removeTagFromText`. I'm guessing it's a syntax error in my checklists somewhere? Can you tell me more or how to identify?

Error:
`TypeError: Cannot read property 'replace' of undefined`

Stacktrace: 
<img width="530" alt="Screen Shot 2021-05-03 at 3 30 40 PM" src="https://user-images.githubusercontent.com/877820/116851172-87148080-ac24-11eb-9e39-101e3c95ef20.png">

**Comment by delashum** [comment]
Hmm, I'm not sure what state of data could cause this error. I will try and add some checks around this in the next release, not sure how to reproduce for now though

**Comment by gdouglas** [comment]
It looks like the error happens when inlining a tag and checklist. e.g.
`#todos - [ ] do something`

(also, love the plugin)

**Comment by jshum** [comment]
you can use this search term `/#.*- \[ \]/` in the search bar to search for
these.

or this one `/- \[ \].*#/` if you want to look for occurrence of tag after
the checkbox

I removed all instances of these occurring for me, but didn't fix it for me
yet
