### ISSUE TITLE
Empty line problem with Markdown prettifier for Obsidian

### ISSUE THREAD

**Issue by IgnatzG** [delashum/obsidian-checklist-plugin#53]
since Markdown prettifier for Obsidian is adding an empty line after a heading the checklist does not recognise the list any more: 

before: 
#todo 
- [x] check Git server

after:
#todo

- [x] check Git server

**Comment by delashum** [comment]
I fixed this issue in #26 and can't reproduce on my end. The plugin will check for any checklist items within one space after a matching tag. so as long as you only have one empty newline between them it should be able to parse just fine.
