### ISSUE TITLE
Less vertical space between to dos

### ISSUE THREAD

**Issue by torstenkoepke** [delashum/obsidian-checklist-plugin#6]
Great work, thanks so much!  
Is there a way to reduce the vertical space between the tasks to get a denser appearance?

**Comment by delashum** [comment]
Yeah, that's a good idea! i'll add an option for a condensed view

**Comment by delashum** [comment]
Added a setting called `Look and Feel` which you can set to `Compact`. Will be included in `1.0.8`

**Comment by torstenkoepke** [comment]
Thanks - works like a charm
