### ISSUE TITLE
[feature request] exclude files in templates folder

### ISSUE THREAD

**Issue by cfjrb** [delashum/obsidian-checklist-plugin#62]
I think this one is probably easy to implement.   

It would be nice to be able to exclude files in my templates folder from the search.  

BTW, thanks for a great plugin! 

Nevermind!  I see you were way ahead of me.  Good job!

**Comment by delashum** [comment]
You can already do that :) Go to settings for the plugin and you will see an option for `Ignore Files`. It's the 5th one down
