### ISSUE TITLE
[Bug] doesn’t work in mobile app

### ISSUE THREAD

**Issue by delashum** [delashum/obsidian-checklist-plugin#63]

**Comment by ekmekjian** [comment]
This is one of my favorite plug-ins I really wished it worked on obsidian mobile.

**Comment by delashum** [comment]
same 😕

unfortunately i haven't been able to find a good way to debug on mobile so i don't have any leads as to what's wrong. this is top of my list when i get some time though. if anyone has any ideas i'm open to suggestions.

**Comment by jeffvogelsang** [comment]
Hi @delashum, I saw this on the Obsidian discord. It looks like it could help you get logs from the plugin on mobile that you can then examine on a desktop: https://gist.github.com/liamcain/3f21f1ee820cb30f18050d2f3ad85f3f

**Comment by delashum** [comment]
I finally found the issue. I wasn't having any success with that `console.log` monkey patch, and it seemed like the error was happening at a higher level than that. I finally tracked it down to a `require('utils')` which a dependency (`markdown-it-regexp`) used. I rewrote that dependencies code using modern TS and things are working now! I guess mobile doesn't support `utils`.

I have the plugin successfully running on mobile, but for some reason the styles are really messed up (it almost seems like flexbox isn't being respected on mobile). So as soon as I get the styles all sorted out I'll draft a new release.

Thanks for your patience!

**Comment by delashum** [comment]
I just released `1.2.3` which fixes this. For some reason the styles are messed up on mobile and I haven't been able to figure that out yet. I opened #78 where we can track that issue. I figured it would be better to at least release this fix for now.
