### ISSUE TITLE
Extremely high memory usage 

### ISSUE THREAD

**Issue by jimclay75051** [delashum/obsidian-checklist-plugin#65]
I like the plugin. The only problem is that it causes Obsidian's memory usage to skyrocket when it is first opened. Without the plugin the memory used is around 300mb, but with this plugin in the memory will go as high as 1500mb before falling back down to around 300mb and then going back up.  The memory does eventual settle down to 300mb, but I don't think you mean for it skyrocket like that.

With memory spiking:
<img width="732" alt="Snag_18ce6cf" src="https://user-images.githubusercontent.com/30031026/123559531-2a37d100-d762-11eb-9c01-0ec1044cf2c9.png">

After memory has settled down:
<img width="754" alt="Snag_18e3d57" src="https://user-images.githubusercontent.com/30031026/123559563-5eab8d00-d762-11eb-88b2-131da1cbee67.png">

**Comment by delashum** [comment]
Hmm, this is interesting. I do have to load the entire file contents of each file that has a matching `#todo` tag, but that doesn't explain the spike. I'll have to look at this

**Comment by delashum** [comment]
On my machine (Mac) I don't see any spike. It stays constant at around 250 MB through the entire startup.

Do you have the todo tag in settings set to empty? This will cause every file in your vault to be parsed.
Or, do you have a very high number of files in your vault? I have about ~250 for reference and am not seeing any perf issues.

**Comment by jimclay75051** [comment]
Hello, you are correct. With the Tag name field set to "#todo" there is no problem. But the moment I delete the tag name, the memory starts to climb. And when I put the tag name back in, the memory fairly quickly goes back to normal.

Thank you. I hope this helps you with your plugin.

**Comment by delashum** [comment]
If that's the case I'm not sure there is too much I can do. If your intention is to have every single file parsed, then I have no option but to load them into memory since I have to scan the entire file to search for checklists.

Another alternative for you would be to use the `Include Files` or `Ignore Files` options in the plugin settings. With this you can narrow down which files the plugin is parsing.

**Comment by jimclay75051** [comment]
This is fine. I didn't realize that was the cause. Thank you.
