### ISSUE TITLE
Checklist retains black font making it not visible in the panel of Red Graphite theme

### ISSUE THREAD

**Issue by Guvna-McBacon** [delashum/obsidian-checklist-plugin#66]
Using the [Red Graphite](https://github.com/seanwcom/Red-Graphite-for-Obsidian) theme. In light mode black text doesn't show. I'm not a coder, so not sure if this is an issue to be solved for Red Graphite or Checklist and will cross-post.

Checklist is one of the most useful plugin for how I work,

Cheers

![Screenshot 2021-06-28 125812](https://user-images.githubusercontent.com/86627713/123696383-8d803c80-d810-11eb-9949-4f9e3a8171fa.png)

![Screenshot 2021-06-28 125821](https://user-images.githubusercontent.com/86627713/123696397-9244f080-d810-11eb-9cae-cef18e5fff09.png)

**Comment by delashum** [comment]
The plugin supports custom styles fairly well. You should be able to add some simple custom CSS to fix this. See this thread for some tips: https://github.com/delashum/obsidian-checklist-plugin/issues/13

**Comment by Guvna-McBacon** [comment]
Thanks!
