### ISSUE TITLE
How to turn on the Checklist pane?

### ISSUE THREAD

**Issue by dabingxx** [delashum/obsidian-checklist-plugin#69]
Sorry for the stupid question. I know it is in the right bar, but once being closed, I can't find a way to turn it back on. I got to turn off then turn on the plugin to make it visible again. 
Is there a command or hotkey? Thank you.

**Comment by delashum** [comment]
Hmm, I didn't really plan for the use case of closing the pane and wanting to reopen it, but that totally makes sense. Personally I don't ever close it, I just collapse the right sidebar so it's not an issue. But I can add a command for it, that's a good idea

**Comment by dabingxx** [comment]
Thank you @delashum ! 
The reason I need to close it was that the right pane is also shared with the backlink pane. Therefore occasionally I need to close the checklist to have more space for the backlink.

**Comment by furlan** [comment]
Actually in my case, the panel is closing by itself. Also, at the same time, appear a message "No file is open".
I don't know if it's a particular case of my environment or a bug.
(Windows version - 12.15, with Git sync for the vault content).

**Comment by delashum** [comment]
duplicate of #24, adding updates there for those who are interested
