### ISSUE TITLE
Collaborate with Slated plugin

### ISSUE THREAD

**Issue by tgrosinger** [delashum/obsidian-checklist-plugin#7]
Hey @delashum, I just found your plugin and noticed that it has a lot of similarities with the feature I am starting on in [Slated](https://github.com/tgrosinger/slated-obsidian). Here's the task, but it doesn't have a lot of detail written up: https://github.com/tgrosinger/slated-obsidian/issues/25

Let me know if you want to discuss collaborating! You can find me in the Obsidian Discord too.

**Comment by delashum** [comment]
What does collaboration mean? Seems like that ticket is more or less to build what my plugin is doing.

**Comment by tgrosinger** [comment]
Slated is very focused on daily notes. I'm working on adding a view which allows users to view and interact with their overdue and upcoming tasks. I imagine in the future having the ability to move tasks between daily notes and weekly notes.

Your plugin seems to be broader, dealing with checklist items anywhere in the Obsidian Vault, and less focused on a daily todo list workflow. So we have a number of operations in common, such as parsing tasks from files and modifying them, but I believe we'll end up wanting a different user experience in the view.

So as a long winded answer to your question, collaboration could mean several things. It probably means having a discussion so we understand the goals and direction of each plugin. Then it might mean something like adding an API between our plugins or a shared library which allows reuse of common functionality. Slated currently does this with the Calendar plugin and it has saved me a ton of effort!

And of course, no action is also an option. I just wanted to reach out 🙂

**Comment by delashum** [comment]
Yeah, that makes sense. I'm pretty slammed lately, and don't think I'll have the time to coordinate and get that organized on this so I'm going to pass for now. Maybe if things slow down in the future. Best of luck on your ticket!
