### ISSUE TITLE
Enabling this plugin causes intermittent freezing when typing

### ISSUE THREAD

**Issue by Scatchell** [delashum/obsidian-checklist-plugin#70]
I love this plugin! But I've had trouble when enabling this plugin where it causes Obsidian to stop responding regularly for a small period of time.

I have disabled all the plugins one by one to see which was the culprit and disabling this pluging is the only thing that stops this behavior.

For instance, when typing a sentence e.g. "this is a test sentence I would like to test with" Obsidian would show the letters I was typing up to "this is a test sentence I would like " and be frozen there, showing no updates even as I continued typing, for about half a second to one second. Then, it would suddenly completing the rest of the sentence and start reflecting the changes I was typing again.

I have tried this on two different computers (one much more powerful than the other) with the same Obsidian vault, and have found the exact same behavior.

I am not sure if this bug has been noticed before, or how exactly to reproduce it on a test vault, but I have a relatively large number of checklists across many files (am unsure if this might be the reason.) Other plugins seem to work fine with my vault.

Any help would be much appreciated and I am happy to help debug to find the source of the problem as this is a very useful plugin but I've had to keep it disabled due to this behavior.

I'm using the Mac version of Obsidian:

Obsidian version: v0.12.10
Checklist plugin: 1.2.2

**Comment by Scatchell** [comment]
I wanted to add one quick thing, I have left blank the tag filtering (which defaults to only search notes marked with #todo ) so it searches all notes instead. Image posted below to explain what I mean.

![image](https://user-images.githubusercontent.com/1375869/126984750-99824a57-39f8-4bcc-8716-2a0b9016e68e.png)

With a relatively large vault, maybe this issue is reproducible by doing the same and removing the tag so all note files are searched.

One simple solution might be to be able to be able to configure how often the todo's update (e.g. a 1 second freeze once per hour could be much more reasonable even if it meant I don't always have the todo's perfectly up to date.)

Another thought is lazilly loading the todo's when focus is given to the todo tab instead of periodically searching all files.

**Comment by Scatchell** [comment]
In case there is any interest, I have forked your code and was able to reproduce the problem locally with a test vault that has 20 or 30 different files all with a lot of checkboxes. It doesn't seem a particularly unreasonable amount of todo items to have.

I get this behavior on multiple machines including one recently bought and essnetially with a fresh installation of OS X so don't believe it is related to any local issues on my machine or hardware limitations.

I can attach the test vault here if there is interest. I was looking into fixing it myself but am unfamiliar with the code, so though I have found an area that I think is causing the problem I'm not sure which change to make. If I figure anything out I can submit a PR.

Happy to give more info if someone more familiar with the code is willing to take a look at this with me.

**Comment by delashum** [comment]
Hi, thanks for the detailed reproduction of this issue. I will likely look into this one next as it seems pretty serious. That definitely shouldn't be too many files. I have probably close to 200 files in my main vault and lots of checklists all over and never see this issue. If you have a way to send me the test vault you are using that would be really helpful for me while working on this.

**Comment by delashum** [comment]
Looking into this some more, the truth is the algorithm isn't very efficient and doesn't really cache things. Meaning when changes are made it's going to re-scan and parse every checklist in your vault. I am going to rewrite things to be more efficient, but this will likely take a little while. Will post updates here

**Comment by rturquier** [comment]
I installed the plugin today on a large vault (2400 files, many of them are not markdown files).
When I set "tags" setting to "catch-all", it caused the obsidian window to turn completely white and stop responding, about 20 seconds after launching the app.
I had to manually delete the plugin folder. 

My guess is that this might come from the algorithm not being very efficient.
I will try installing again when you have a better algorithm :)
Thank you for your great work!

**Comment by Scatchell** [comment]
Hey delashum - thanks for looking into this! I am guessing you don't need the test vault I used, but if you do still want it, I am happy to send it over.

One thought I had is, if it would require a significant rewrite to make more efficient, maybe there could be a two step process to fix this - one quicker solution that makes the plugin usable again, and the other that introduces caching or makes the algorithm more efficient.

For instance, when I was looking at the code I was wondering if the block that seems to be called to recalculate all the checklist items:

```
  $: {
    rerenderKey
    if (firstRun) setTimeout(recalcItems, 600)
    else recalcItems()
  }
```

If this block only ran recalcItems in the case that more than 5 minutes had passed since the last recalc, it would probably make it usable for people while the more inherent problem is being fixed.

Another thought I had was if the recalc could be triggered by a keyboard shortcut, or when the checklist pane itself was given focus, instead of updating every change - then the pauses would be much more reasonable to deal with.

Just a thought though!

Thanks again for this idea and continuing work on it, it's one of my fav plugins so far :-D

**Comment by delashum** [comment]
I think that could be an interesting intermediary solution. Maybe there is an option in settings for `auto refresh` which you could toggle off and associated command to manually refresh it.

Another quick fix I was going to try is see if I can jam this all into a service worker and run things behind the scenes. Not sure if that's viable, but I do agree getting something out there while a real fix is happening is probably the right strategy

**Comment by delashum** [comment]
Pinging this because it's been too long since an update. Unfortunately I am swamped in my personal and work life and haven't had time to look at this very much yet :( Hopefully I will have some free time this weekend to dive into it. Still on my mind though!

**Comment by ianscottknight** [comment]
I am also running into this issue and would love to see a solution.

**Comment by delashum** [comment]
I spent some time this week working on this problem and have a caching solution implemented. I created a test vault with 10k+ files all with checklists in them and can definitely reproduce the freezing that happens. With the caching solution the time obsidian is locked up after an edit is significantly decreased, but still present on my test vault. I think the only way to realistically have no jitter on very large vaults is to figure out how to get the script into a worker. I am tinkering with a few solutions there but will push this caching solution in the meantime in a release this week and hopefully unless you have 10k files with checklists in them this should greatly improve performance!

Thanks for your patience, I know this is a frustrating issue.

**Comment by delashum** [comment]
I will also a new setting option called `Auto reload` which will default to `true`. If you turn this off there will be a command you can use to manually refresh the list at larger intervals. For people who still have issues even after caching can use this in the meantime while I work on background processing.

**Comment by delashum** [comment]
Note: The caching solution will not help the initial load on large vaults, only subsequent loads as you edit files as it will only re-parse that individual file.
