### ISSUE TITLE
BUG: numbered cheklists.

### ISSUE THREAD

**Issue by thelegend09** [delashum/obsidian-checklist-plugin#71]
Seriously, I'm so glad this plugin exist. Thanks dev!!

This otherwise amazing plugin doesn't work when you use numbered checklists like "1. [ ] Do this or that." Also, if I use numbered checklists first in a document, it stops recognizing the normal checklists after.

Here’s a gif of my experiment. 

![2021-07-22-171200](https://user-images.githubusercontent.com/71288870/126710569-cc9305b3-7e50-4603-82b7-7a070758e849.gif)

**Comment by delashum** [comment]
Hmm, yeah I never considered numbered checklists. Is that a part of the markdown spec? If so I can update to include this
