### ISSUE TITLE
Setup for Svelte Plugin Development

### ISSUE THREAD

**Issue by mochsner** [delashum/obsidian-checklist-plugin#72]
I've gone through a series of organization strategies (onenote, evernote, org mode, vimwiki, notion, and finally obsidian). This plug-in has helped me solify my development tracking experience, so I first just wanted to say thank you.

From my time spent trying to work on organizational strategies, there's a few things I would love to play around with in this plugin and see how complex they'd be to add before turning them into issue requests, but I must admit that svelte is new to me (I've heard **great** things). 

I'm unfortunately just a bit involved with other things to play around with trying to build this app locally. **At a basic level, are there any build steps I can follow? I'd be happy to clean it up, expand on it (scerenshots), and create a PR to add this in for future contributors as well for the help.**

**Comment by Spectralgo** [comment]
Same here, it helps a lot with my productivity setup. I would love to help. Thanks for this plugin app :)

**Comment by delashum** [comment]
I would very much welcome some help. I built this in a weekend intending to only use it personally, and as you can probably tell by the open issue count I'm a bit behind on maintaining it. I really only have time to hop on once a month or so and tackle the one or two most pressing issues. There is a lot of awesome feature ideas that I would love for someone else to pick up.

Here is my development process:
1. `npm i`
2. `npm run dev`
3. copy and paste the outputted `main.js` into the plugin file in my test obsidian vault.
4. run the command to reload obsidian
5. repeat 3 & 4 as changes are made

I'm also not a Svelte developer, but found it pretty intuitive coming from React. `App.svelte` is pretty much the entry point for everything. It calls the function `parseTodos(...)` which is where all of the logic happens. I'm a big TS fan, so everything should have up-to-date types which hopefully makes diving in bit easier. Again, as this was a weekend project for me I know things get a bit hairy once you get into `parseTodos(...)`, so I apologize about that :|

Is this enough information to at least get things up and running locally?

**Comment by mochsner** [comment]
This is perfect, thanks @delashum ! I'm not on my personal dev machine right now to actually run it, and may not have a chance tonight unfortunately, but I'll be sure to check this out as soon as I can this week to start out. Even though you got this much documented, I'd love to keep this open until we have something a bit more formal written up. I've added you both to my fork where I plan to work on some of the documentation bits to be merged later, so feel free to push to it as you wish!

Also, @Spectralgo -- I'll plan to paste anything else (less formal/official) in here that I discover, such as svelte references, etc. for the time being. If you find anything interesting or useful that was good for you, feel free to share as well!

**Comment by mochsner** [comment]
Are you guys running this on Linux, Mac, or Windows? I've got the code working on my Linux laptop and documented that pretty thoroughly, but I don't really have Windows covered yet.

I've created docs/ with a SETUP.md for the development instructions on Windows/Linux (sort of manual on windows as described above), and a contributing.md for general contribution guidelines.

Also, @delashum - any particular thoughts on contribution guidelines? I've got the following right now. I can just create PR and you can update it as you see fit.

## Issues
1. Create issue for review in [delashum/obsidian-checklist-plugin/issues](https://github.com/delashum/obsidian-checklist-plugin/issues)
2. If issue is approved for development, follow process below.

## Development
See SETUP.md for guide on getting your development environment setup.

## Pull Request Workflow
1. Create a fork of the the repository
2. Make changes in your fork, tagging the #NUM of the issue in question.
3. After testing development, go to your fork, and on your branch to be merged you should see "This branch is # comit ahead of delashum:master". To the right you can click 'Contribute' to open a **Pull Request** for your changes.
4. Work with Delashum or any other maintainers to merge your changes in.

**Comment by mochsner** [comment]
NOTE: removing package-lock.json shouldn't affect anything from a deployment perspective, but you might want to just be 100% sure, even though this change doesn't need to go to release.

**Comment by Spectralgo** [comment]
Hey @mochsner, I followed the SETUP.md instructions and **it worked** but only when I deleted the package-lock.json file. 

I get this error message in my terminal: if I let the package-lock for the npm install command:

> npm WARN tarball tarball data for obsidian@https://github.com/obsidianmd/obsidian-api/tarball/master (sha512-09/Zpb7sXE264OLk3DDbieU895d6NaNIIL8eyKR+5WpXPSYKeDfwy4yQh3WSb6KHWTJpbyvqUDchh8Yy4lHiRQ==) seems to be corrupted. Trying again.
npm ERR! code EINTEGRITY
npm ERR! sha512-09/Zpb7sXE264OLk3DDbieU895d6NaNIIL8eyKR+5WpXPSYKeDfwy4yQh3WSb6KHWTJpbyvqUDchh8Yy4lHiRQ== integrity checksum failed when using sha512: wanted sha512-09/Zpb7sXE264OLk3DDbieU895d6NaNIIL8eyKR+5WpXPSYKeDfwy4yQh3WSb6KHWTJpbyvqUDchh8Yy4lHiRQ== but got sha512-uUVTUpsk+LqhCdPJCxBwOuQ3cXOf63vbman1iOa/X6cjEguzqIsv+nomMZVnrmyXedbP1hM+YJYYh+gVSrKAlg==. (15907 bytes)


Do you know why?

**Comment by mochsner** [comment]
Maybe? For me, using package-lock.json requires admin permissions, whereas just using the package.json did not.

If you're on Linux, did you do sudo npm install?

My thought was that something about the package-lock.json having EXACT package versions might make it a higher security risk to run, therefore requiring more permissions.

**Comment by Spectralgo** [comment]
I'm on Windows. I tried with PowerShell in admin mode and wsl.exe with sudo. It was the exact same error message in both cases.

**Comment by mochsner** [comment]
Ah, this brings up a good point @Spectralgo ! On windows, since sudo for administrative priveleges doesn't exist, it might need to be approached a different way. When you're running powerrshell, can you open it this way?
![image](https://user-images.githubusercontent.com/19310711/132281228-2f80aea9-a33e-4537-8f97-7f9b6d0c290f.png)

Alternatively, if you really want to try to use powershell within an embedded window (e.g. VSCode terminal), you might try ` start-process PowerShell -verb runas` to launch powershell as admin. I've sometimes had issues with this sort of thing in server administration though, so just launching as admin to begin with is always the best bet.

If that works, we can be sure to update the instructions :) Let us know!

**Comment by Spectralgo** [comment]
It worked with the PowerShell started with the command you provided. 
```start-process PowerShell -verb runas```

But it didn't work with the "PowerShell run as admin" using the Windows explorer UI.

You can see, in the windows title bars, both are prefixed with ```Administrator:```

![image](https://user-images.githubusercontent.com/56794425/132379849-a617f768-a725-4e80-9cf3-63853d03ae1a.png)

I had also tried to make it worked by launching PowerShell (and cmd.exe) as administrator using the UI on another laptop and had the same result.

It may be a good idea to mention this quirk in the Setup.md.

Thanks for the help @mochsner. 🙏
