### ISSUE TITLE
plugin can't be loaded on mobile app (iOS)

### ISSUE THREAD

**Issue by netlynker** [delashum/obsidian-checklist-plugin#75]
Hi,

Plugin can't be loaded on mobile editor on iOS with the message "Failed to load obsidian-checklist-plugin". In setting it is disabled. Enabling it fails with same error message. 

Regards,

**Comment by cstromblad** [comment]
(For me Android and ChromeOS)

**Comment by mochsner** [comment]
Isn't this a duplicate of #63 ?

**Comment by delashum** [comment]
yep, see #63 for updates
