### ISSUE TITLE
Styles are messed up in mobile app

### ISSUE THREAD

**Issue by delashum** [delashum/obsidian-checklist-plugin#78]

**Comment by delashum** [comment]
I don't really have any clues as to what's going wrong at the moment. My current strategy is going to be to employ some trial and error and see if I can make some progress. Will post updates

**Comment by mochsner** [comment]
@delashum what mobile platform (iOS/Android) are you trying on? All browsers on iOS (even chrome on iOS) are technically based in Safari's engine, so if you're on iOS, that could be the reasoning for some skew between things. 

(Anyways, if this is the case, which probably isn't the issue, it may be that a desktop version of safari could diagnose it easier).

**Comment by delashum** [comment]
@mochsner I am using it on an iOS device. Can anyone confirm if the styles look like the image in #84 on non iOD mobile devices? Or are they rendering properly?

**Comment by mochsner** [comment]
Ah yeah looks the same. Screenshot:![Screenshot_20211005-190605.png](https://user-images.githubusercontent.com/19310711/136120396-42f89c2b-363b-4434-9adb-ffde9e02279c.png)

**Comment by mochsner** [comment]
I've noticed it seems to be breaking on - and spaces almost every time. Maybe there's a soft wrap setting somewhere you can override to just make it single line checklists for now? Like "word-wrap: nowrap !important;" or something?

If it's a tables / flex box conflict of some sort, then until debugging on mobile is a bit easier to let you poke at the CSS in HTML, it's going to be hard to diagnose (I wish I knew more about debugging on mobile to help, sorry)

**Comment by JepheDelPhuego** [comment]
Has there been any progress for this on mobile?

**Comment by OllieA** [comment]
I have a bunch of different themes on my iPad and found that one of them (Sanctum) displays the TODO list properly (narrow column for checkbox and wide for description). All of the other themes display the buggy version (wide column for the checkbox and narrow for the description). Hopefully this contains a clue for fixing the bug.

**Comment by delashum** [comment]
Well I found the issue. They added a new `mobileEmulation` flag you can set and turns out for mobile they add the style
```
button {
  width: 100%
}
```
and since the collapse icon and the complete icon are both buttons it messes things up. Fix coming in next release!
