### ISSUE TITLE
Look weird in ying & yang theme after today's update

### ISSUE THREAD

**Issue by shaggyfeng** [delashum/obsidian-checklist-plugin#79]
V1.2.3
![Screenshot (199)](https://user-images.githubusercontent.com/75353922/129317209-922de80e-85c9-4616-a4ae-c35144faca26.png)

V1.2.2
![Screenshot (200)](https://user-images.githubusercontent.com/75353922/129317248-2f4d982d-29c2-42ee-bb35-e43fb1508146.png)

**Comment by delashum** [comment]
Well that's odd. I haven't touched the styling file in a couple releases so not sure how this is possible. Will look into it.

**Comment by delashum** [comment]
I looked into this a bit and from what I'm seeing we haven't changed anything on our end that would cause this. I noticed that theme had a release 2 days ago with some styling changes. Is it possible you updated the theme and plugin at the same time? I can definitely see the offending styles but they are coming from the themes stylesheet.

**Comment by shaggyfeng** [comment]
> I looked into this a bit and from what I'm seeing we haven't changed anything on our end that would cause this. I noticed that theme had a release 2 days ago with some styling changes. Is it possible you updated the theme and plugin at the same time? I can definitely see the offending styles but they are coming from the themes stylesheet.

I rolled back the checklist plugin to v1.2.2, then everything works just fine. In fact, I rolled back the theme to test it as well. It seems somehow it is the v1.2.3 checklist which is causing it.

**Comment by shaggyfeng** [comment]
I will let the yin & yang developer know it as well.

**Comment by shaggyfeng** [comment]
> I looked into this a bit and from what I'm seeing we haven't changed anything on our end that would cause this. I noticed that theme had a release 2 days ago with some styling changes. Is it possible you updated the theme and plugin at the same time? I can definitely see the offending styles but they are coming from the themes stylesheet.

The theme author fixed it. It is all good now.
