### ISSUE TITLE
Installation not working over Community Plugins

### ISSUE THREAD

**Issue by mogelschrift** [delashum/obsidian-checklist-plugin#8]
The installation of the new update / the plugin generally isn't working atm. 
(I can however install every other plugin).

Any idea?

**Comment by delashum** [comment]
Thanks for bringing this up. I misunderstood how new releases work, and had my version numbers off by one. I just resolved that, however I am getting issues on all plugin installations at the moment, so I can't say for certain if that update worked

**Comment by mogelschrift** [comment]
Yes it works now. You need to update obsidian to the newest version. GitHub updated some download servers yesterday, the new update corrects the community plugin section

**Comment by delashum** [comment]
oh okay, thanks. glad it's working again though
