### ISSUE TITLE
Circle nonstop

### ISSUE THREAD

**Issue by gitophile** [delashum/obsidian-checklist-plugin#80]
Reload recent update 1.2.3 on iPAD Pro new silicone 14.6 and get a nonstop circle just below where output should show.  Doesn’t stop other Obsidian function.

**Comment by gitophile** [comment]
See related to #63

**Comment by gitophile** [comment]
Actually maybe I will reopen as 1.2.3 was to fix a few things.

**Comment by delashum** [comment]
Yeah if you are on `1.2.3` and still seeing this issue then let's keep this open. I'll take a look when I find some time

**Comment by bblais** [comment]
I'm getting this now on version 2.02 on a mac -- recent update perhaps?  Not sure how to debug this.

**Comment by gmaciocci** [comment]
Getting the same thing on 2.02 on Windows 11. Uninstalling and reinstalling sometimes works, and sometimes it does not, but the issue always comes back. My notes are stored on a locally synched iCloud folder if that makes any difference.

**Comment by Ogolar** [comment]
same Problem here
