### ISSUE TITLE
Update Examples

### ISSUE THREAD

**Issue by BurritoAssassin** [delashum/obsidian-checklist-plugin#82]
This is a low priority improvement.  Some of the help text & visual examples are inconsistent, which can be confusing for new users.

Here's the Tag Name info from the plugin's General Settings:

```
Tag Name
_e.g. #todo.  Leave empty to capture all_

Default Field Value:  todo  (should be #todo based on the example)
```

One more: the screenshots for the plugin installation page use "#mytodo" as the list name instead of #todo

**Comment by delashum** [comment]
Yeah, Those definitely need to be updated. There's some new functionality they don't show either.

**Comment by mochsner** [comment]
@BurritoAssassin did you want to open a PR to add this documentation in? I did something similar for development documentation (and Github PR documentation). Check out the `docs/` folder in main branch, and the `.md` files in there for instructions!
