### ISSUE TITLE
The format of the todo list in IOS is messy

### ISSUE THREAD

**Issue by Dolores-Z** [delashum/obsidian-checklist-plugin#84]
![647B678B-F2D4-4B3A-8112-6D256AA33930](https://user-images.githubusercontent.com/89349762/130361783-e8338d63-73b5-41c3-96bb-f8ea870fb73c.jpeg)

**Comment by mrkteq** [comment]
+1

**Comment by tristancade** [comment]
+1

**Comment by delashum** [comment]
This is technically a duplicate of #78, thanks for adding the screenshot to illustrate the issue
