### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by kinbiko** [delashum/obsidian-checklist-plugin#85]
Could you add a license please?

If you're not sure which one to choose, [this site might help](https://choosealicense.com/).

**Comment by kinbiko** [comment]
I like syncing my notes (incl. `.obsidian/`) via git, but without a license it's not clear that I have the rights to use your plugin or distribute it as part of my own (non-public) repository.

**Comment by osslate** [comment]
+1

@delashum A license gives legal clarity both to users and contributors around what circumstances we're allowed use the plugin, if we're allowed to modify and/or redistribute the code, etc.

The website @kinbiko linked is a good start. Another good resource is [the OSI](https://opensource.org/licenses). I usually stick to one of GPL, MPL, or Apache licenses personally :)

**Comment by delashum** [comment]
MIT license added
