### ISSUE TITLE
Opening files in which tasks sit when grouping by tags

### ISSUE THREAD

**Issue by torstenkoepke** [delashum/obsidian-checklist-plugin#9]
I love the possibility to jump to the file of a task via clicking the 'headline' of a task - unfortunately this is not possible when grouping by tag - which I also like a lot.   Am I missing something here or would you have an idea how to combine the two elements, i.e. grouping by tags and integrating the file jump?

I know, this goes against my other issue of having a more condensed view, life is hard sometimes :=)

**Comment by delashum** [comment]
Yes, i have some ideas on how to incorporate this. Maybe be a week or two though

**Comment by hson** [comment]
Perhaps enabling click on the text of a specific task could bring you to the file (and section) of that task?

I found it confusing that the task disappeared when clicking on the text at first. Clicking the checkbox part should of course still complete the task.

**Comment by delashum** [comment]
Forgot to tie the commit to this, but addressed in latest version
