### ISSUE TITLE
Code review

### ISSUE THREAD

**Issue by lishid** [delashum/obsidian-checklist-plugin#90]
Sending back some code review feedback from another plugin:
> Don't keep a reference to your view, as you might have a reference to an outdated/detached view. Instead, use workspace.getLeavesOfType(MY_VIEW_TYPE) to get live references to your views.

https://github.com/delashum/obsidian-checklist-plugin/blob/eaf140820d4302b2f65c3123853a40318f49fa46/src/main.ts#L9
More context here: https://github.com/obsidianmd/obsidian-releases/pull/504#issuecomment-933749727

---
https://github.com/delashum/obsidian-checklist-plugin/blob/eaf140820d4302b2f65c3123853a40318f49fa46/src/main.ts#L34
You don't actually need to call this - when your view detaches it will be unloaded. You can also use `workspace.detachLeavesOfType(MY_VIEW_TYPE)` as a shortcut to close all the views.

**Comment by delashum** [comment]
Thanks for the heads up, I'll get these changes made in the next release
