### ISSUE TITLE
Font size in sidebar more compact

### ISSUE THREAD

**Issue by Superfeuchter** [delashum/obsidian-checklist-plugin#98]
I'm reorganizing many notes, so it could be useful to have a smaller font-size in the sidebar.
Although I use the compact view, I have to scroll up and down all the time.
This is a very useful plugin, by the way.

**Comment by delashum** [comment]
Most of the plugin is very customizable via the included css vars. I will add one in the next release called `--todoList-contentFontSize` which you can override to change the font size. The todo item font size defaults to the editor font size currently

**Comment by Superfeuchter** [comment]
Thank you!
